spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/spring-store?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
#  pattern:
#    console: |
#      [ %thread ]
#         %-5level
#         %logger{36} -
#         %msg
#      -------------====------------